import React from "react";
import Navbar from "../components/Navbar";
import LightRays from "../components/LightRays";


const TermsAndConditions = () => {
  return (
    <>
    <LightRays/>
      <Navbar />
      <main className="px-[5%] md:px-[10%] lg:max-w-screen-xl lg:mx-auto py-16">
        <h1 className="text-3xl md:text-4xl font-black mb-6">Terms & Conditions</h1>
        <p className="text-sm opacity-80 mb-8">
          This document is an electronic record under the Information Technology Act, 2000.
          It is generated by a computer system and does not require physical or digital signatures.
        </p>

        <section className="space-y-6 leading-relaxed">
          <p>
            These Terms of Use (“Terms”) govern your access to and use of{" "}
            <a href="https://royalmusicalstudios.vercel.app/" className="underline">
              https://royalmusicalstudios.vercel.app/
            </a>{" "}
            and related mobile experiences (the “Platform”) operated by Royal Musical Studios,
            Adgaon Bk, Akola, India (“Royal Musical Studios”, “we”, “us”, or “our”). By accessing
            or using the Platform, you agree to be bound by these Terms and the policies referenced
            here.
          </p>

          <h2 className="text-xl font-bold">1) Eligibility & Account</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>You must be capable of forming a legally binding contract under Indian law.</li>
            <li>
              You agree to provide true, accurate, and complete information during registration and to
              maintain the security of your account. You are responsible for all activity under your account.
            </li>
          </ul>

          <h2 className="text-xl font-bold">2) Services & Transactions</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              By placing an order or booking a service, you enter into a binding contract with us for the relevant
              product/service, subject to these Terms and applicable policies.
            </li>
            <li>You agree to pay all fees, taxes, and charges associated with your order or service.</li>
          </ul>

          <h2 className="text-xl font-bold">3) Content & Intellectual Property</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              The Platform (including design, layout, look, graphics, text, and software) is owned by or licensed to us
              and protected by applicable IP laws. No rights are granted to you except as expressly stated.
            </li>
            <li>You may not copy, modify, distribute, reverse engineer, or create derivative works of the Platform.</li>
          </ul>

          <h2 className="text-xl font-bold">4) Acceptable Use</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>Do not use the Platform for any unlawful or prohibited purpose.</li>
            <li>Do not interfere with or disrupt the Platform or its security features.</li>
          </ul>

          <h2 className="text-xl font-bold">5) Third-Party Links</h2>
          <p>
            The Platform may contain links to third-party sites for your convenience. Their terms and privacy practices
            apply when you visit them. We are not responsible for their content, policies, or practices.
          </p>

          <h2 className="text-xl font-bold">6) No Warranties</h2>
          <p>
            The Platform and Services are provided “as is” and “as available”. While we aim for accuracy and timeliness,
            we do not warrant completeness, reliability, or suitability for any particular purpose, to the fullest extent
            permitted by law.
          </p>

          <h2 className="text-xl font-bold">7) Limitation of Liability</h2>
          <p>
            Your use of the Platform is at your sole risk. To the maximum extent permitted by law, we are not liable for
            any indirect, incidental, special, consequential, or punitive damages arising from your use of the Platform or Services.
          </p>

          <h2 className="text-xl font-bold">8) Indemnity</h2>
          <p>
            You agree to indemnify and hold harmless Royal Musical Studios, its affiliates, and personnel from any claims,
            losses, or liabilities arising from your breach of these Terms, policies, or applicable law, or your violation
            of third-party rights.
          </p>

          <h2 className="text-xl font-bold">9) Force Majeure</h2>
          <p>
            We are not liable for delay or failure to perform due to events beyond our reasonable control, including acts of God,
            governmental actions, strikes, or network failures.
          </p>

          <h2 className="text-xl font-bold">10) Changes</h2>
          <p>
            We may update these Terms at any time. Continued use of the Platform after changes constitutes acceptance.
            Please review this page periodically.
          </p>

          <h2 className="text-xl font-bold">11) Governing Law & Jurisdiction</h2>
          <p>
            These Terms are governed by the laws of India. Courts in Akola, Maharashtra shall have exclusive jurisdiction over
            all disputes arising from or relating to these Terms and the Platform.
          </p>

          <h2 className="text-xl font-bold">12) Contact</h2>
          <p>
            For concerns regarding these Terms, please use the contact details provided on the Platform or email{" "}
            <a href="mailto:royalmusicalstudios@gmail.com" className="underline">
              royalmusicalstudios@gmail.com
            </a>.
          </p>
        </section>
      </main>
    </>
  );
};

export default TermsAndConditions;
